# Generated by Django 5.0.3 on 2024-03-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('chkin', models.DateField()),
                ('chkout', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('no_of_rooms', models.IntegerField()),
            ],
        ),
    ]
